name: meld

services:
  bun-server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/server
      - ./src:/app/src
      - /app/node_modules
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}

  prisma-studio:
    build: 
      context: .
      dockerfile: server/Dockerfile
    command: ["bunx", "prisma", "studio", "--port", "5555", "--hostname", "0.0.0.0"]
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      bun-server:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    env_file:
      - .env
    command:
      - "http"
      - "--domain=${NGROK_SUBDOMAIN}"
      - "--authtoken=${NGROK_AUTHTOKEN}"
      - "bun-server:3001"
    depends_on:
      bun-server:
        condition: service_healthy
    environment:
      NGROK_DEBUG: "true"
      NGROK_LOG: "stdout"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge